#! /bin/sh
### BEGIN INIT INFO
# Provides:          domotik
# Required-Start:    $remote_fs $syslog
# Required-Stop:     $remote_fs $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Domotik Launche
# Description:       This file launch the domotik WebVie
#                    placed in /etc/init.d.
### END INIT INFO

# Author: Francois Laplaud <flaplaud@lapsys.fr>
#

# Do NOT "set -e"

# PATH should only include /usr/* if it runs after the mountnfs.sh script
SCRIPTPATH=/home/pi/projets/domotik
PATH=/sbin:/usr/sbin:/bin:/usr/bin
DESC="Domotik Controller using RF 433MHz Transmitter"
NAME=domotik
DAEMON=$SCRIPTPATH/Controller.py
DAEMON_ARGS=""
PIDFILE=/var/run/$NAME.pid
SCRIPTNAME=/etc/init.d/$NAME



# Read configuration variable file if it is present
[ -r /etc/default/$NAME ] && . /etc/default/$NAME

# Load the VERBOSE setting and other rcS variables
. /lib/init/vars.sh

# Define LSB log_* functions.
# Depend on lsb-base (>= 3.2-14) to ensure that this file is present
# and status_of_proc is working.
. /lib/lsb/init-functions


case "$1" in
  start)
	[ "$VERBOSE" != no ] && log_daemon_msg "Starting $DESC" "$NAME"
	cd $SCRIPTPATH
	./venv/bin/python Controller.py&
	;;
  stop)
	[ "$VERBOSE" != no ] && log_daemon_msg "Stopping $DESC" "$NAME"
	killall python
	;;
  *)
	#echo "Usage: $SCRIPTNAME {start|stop|restart|reload|force-reload}" >&2
	echo "Usage: $SCRIPTNAME {start|stop}" >&2
	exit 3
	;;
esac

:
